CREATE SCHEMA IF NOT EXISTS PUBLIC;

CREATE TABLE IF NOT EXISTS REPORT (
                                      ID UUID PRIMARY KEY,
                                      NAME VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS CRITERIA_GROUP (
                                              ID UUID PRIMARY KEY,
                                              CRITERIA_GROUP VARCHAR(255) NOT NULL,
    REPORT_ID UUID UNIQUE,
    FOREIGN KEY (REPORT_ID) REFERENCES REPORT(ID)
    );

CREATE TABLE IF NOT EXISTS CRITERIA (
                                        ID UUID PRIMARY KEY,
                                        NAME VARCHAR(255) NOT NULL,
    REPORT_ID UUID NOT NULL,
    CRITERIA_GROUP_ID UUID NOT NULL,
    FOREIGN KEY (REPORT_ID) REFERENCES REPORT(ID),
    FOREIGN KEY (CRITERIA_GROUP_ID) REFERENCES CRITERIA_GROUP(ID)
    );

ALTER TABLE REPORT ADD COLUMN IF NOT EXISTS CRITERIA_GROUP_ID UUID UNIQUE;
ALTER TABLE REPORT ADD CONSTRAINT FK_REPORT_CRITERIA_GROUP
    FOREIGN KEY (CRITERIA_GROUP_ID) REFERENCES CRITERIA_GROUP(ID);